### ISSUE TITLE
401 error without header

### ISSUE THREAD

**Issue by davenojd** [jesmak/posti_tracking#1]
Hey, love the addon!
I seem to have started getting a 401 error, I've doubled checked the credentials and tried removing and re-adding the integration a few times, after some quick debugging with Postman I found the graphql API gives 401 without "x-omaposti-roles" header, I'm not sure if this was added in last couple days by Posti or something, or if you are even able to replicate this issue?

**Comment by jesmak** [comment]
Thanks for reporting this, and thanks for finding the root cause. I was able to reproduce the issue and fix it quickly. There's a new release v1.0.0-beta3 that takes care of this issue. You can also just replace session.py with the latest version.
